using System.ComponentModel;

namespace MauiIcons.Cupertino;
public enum CupertinoIcons
{
    [Description("\ue900")]
    Airplane,
    [Description("\ue901")]
    Alarm,
    [Description("\ue902")]
    AlarmFill,
    [Description("\ue903")]
    Alt,
    [Description("\ue904")]
    Ant,
    [Description("\ue905")]
    AntCircle,
    [Description("\ue906")]
    AntCircleFill,
    [Description("\ue907")]
    AntennaRadiowavesLeftRight,
    [Description("\ue908")]
    AntFill,
    [Description("\ue909")]
    App,
    [Description("\ue90a")]
    AppBadge,
    [Description("\ue90b")]
    AppBadgeFill,
    [Description("\ue90c")]
    AppFill,
    [Description("\ue90d")]
    Archivebox,
    [Description("\ue90e")]
    ArchiveboxFill,
    [Description("\ue90f")]
    Arrow2Circlepath,
    [Description("\ue910")]
    Arrow2CirclepathCircle,
    [Description("\ue911")]
    Arrow2CirclepathCircleFill,
    [Description("\ue912")]
    Arrow2Squarepath,
    [Description("\ue913")]
    Arrow3Trianglepath,
    [Description("\ue914")]
    ArrowBranch,
    [Description("\ue915")]
    ArrowClockwise,
    [Description("\ue916")]
    ArrowClockwiseCircle,
    [Description("\ue917")]
    ArrowClockwiseCircleFill,
    [Description("\ue918")]
    ArrowCounterclockwise,
    [Description("\ue919")]
    ArrowCounterclockwiseCircle,
    [Description("\ue91a")]
    ArrowCounterclockwiseCircleFill,
    [Description("\ue91b")]
    ArrowDown,
    [Description("\ue91c")]
    ArrowDownCircle,
    [Description("\ue91d")]
    ArrowDownCircleFill,
    [Description("\ue91e")]
    ArrowDownDoc,
    [Description("\ue91f")]
    ArrowDownDocFill,
    [Description("\ue920")]
    ArrowDownLeft,
    [Description("\ue921")]
    ArrowDownLeftCircle,
    [Description("\ue922")]
    ArrowDownLeftCircleFill,
    [Description("\ue923")]
    ArrowDownLeftSquare,
    [Description("\ue924")]
    ArrowDownLeftSquareFill,
    [Description("\ue925")]
    ArrowDownRight,
    [Description("\ue926")]
    ArrowDownRightArrowupLeft,
    [Description("\ue927")]
    ArrowDownRightCircle,
    [Description("\ue928")]
    ArrowDownRightCircleFill,
    [Description("\ue929")]
    ArrowDownRightSquare,
    [Description("\ue92a")]
    ArrowDownRightSquareFill,
    [Description("\ue92b")]
    ArrowDownSquare,
    [Description("\ue92c")]
    ArrowDownSquareFill,
    [Description("\ue92d")]
    ArrowDowntoLine,
    [Description("\ue92e")]
    ArrowDowntoLineAlt,
    [Description("\ue92f")]
    ArrowLeft,
    [Description("\ue930")]
    ArrowLeftCircle,
    [Description("\ue931")]
    ArrowLeftCircleFill,
    [Description("\ue932")]
    ArrowLeftRight,
    [Description("\ue933")]
    ArrowLeftRightCircle,
    [Description("\ue934")]
    ArrowLeftRightCircleFill,
    [Description("\ue935")]
    ArrowLeftRightSquare,
    [Description("\ue936")]
    ArrowLeftRightSquareFill,
    [Description("\ue937")]
    ArrowLeftSquare,
    [Description("\ue938")]
    ArrowLeftSquareFill,
    [Description("\ue939")]
    ArrowLefttoLine,
    [Description("\ue93a")]
    ArrowLefttoLineAlt,
    [Description("\ue93b")]
    ArrowMerge,
    [Description("\ue93c")]
    ArrowRight,
    [Description("\ue93d")]
    ArrowRightArrowLeft,
    [Description("\ue93e")]
    ArrowRightArrowLeftCircle,
    [Description("\ue93f")]
    ArrowRightArrowLeftCircleFill,
    [Description("\ue940")]
    ArrowRightArrowLeftSquare,
    [Description("\ue941")]
    ArrowRightArrowLeftSquareFill,
    [Description("\ue942")]
    ArrowRightCircle,
    [Description("\ue943")]
    ArrowRightCircleFill,
    [Description("\ue944")]
    ArrowRightSquare,
    [Description("\ue945")]
    ArrowRightSquareFill,
    [Description("\ue946")]
    ArrowRighttoLine,
    [Description("\ue947")]
    ArrowRighttoLineAlt,
    [Description("\ue948")]
    ArrowshapeTurnupLeft,
    [Description("\ue949")]
    ArrowshapeTurnupLeft2,
    [Description("\ue94a")]
    ArrowshapeTurnupLeft2Fill,
    [Description("\ue94b")]
    ArrowshapeTurnupLeftCircle,
    [Description("\ue94c")]
    ArrowshapeTurnupLeftCircleFill,
    [Description("\ue94d")]
    ArrowshapeTurnupLeftFill,
    [Description("\ue94e")]
    ArrowshapeTurnupRight,
    [Description("\ue94f")]
    ArrowshapeTurnupRightCircle,
    [Description("\ue950")]
    ArrowshapeTurnupRightCircleFill,
    [Description("\ue951")]
    ArrowshapeTurnupRightFill,
    [Description("\ue952")]
    ArrowSwap,
    [Description("\ue953")]
    ArrowtriangleDown,
    [Description("\ue954")]
    ArrowtriangleDownCircle,
    [Description("\ue955")]
    ArrowtriangleDownCircleFill,
    [Description("\ue956")]
    ArrowtriangleDownFill,
    [Description("\ue957")]
    ArrowtriangleDownSquare,
    [Description("\ue958")]
    ArrowtriangleDownSquareFill,
    [Description("\ue959")]
    ArrowtriangleLeft,
    [Description("\ue95a")]
    ArrowtriangleLeftCircle,
    [Description("\ue95b")]
    ArrowtriangleLeftCircleFill,
    [Description("\ue95c")]
    ArrowtriangleLeftFill,
    [Description("\ue95d")]
    ArrowtriangleLeftSquare,
    [Description("\ue95e")]
    ArrowtriangleLeftSquareFill,
    [Description("\ue95f")]
    ArrowtriangleRight,
    [Description("\ue960")]
    ArrowtriangleRightCircle,
    [Description("\ue961")]
    ArrowtriangleRightCircleFill,
    [Description("\ue962")]
    ArrowtriangleRightFill,
    [Description("\ue963")]
    ArrowtriangleRightSquare,
    [Description("\ue964")]
    ArrowtriangleRightSquareFill,
    [Description("\ue965")]
    ArrowtriangleUp,
    [Description("\ue966")]
    ArrowtriangleupCircle,
    [Description("\ue967")]
    ArrowtriangleupCircleFill,
    [Description("\ue968")]
    ArrowtriangleupFill,
    [Description("\ue969")]
    ArrowtriangleupSquare,
    [Description("\ue96a")]
    ArrowtriangleupSquareFill,
    [Description("\ue96b")]
    ArrowTurnDownLeft,
    [Description("\ue96c")]
    ArrowTurnDownRight,
    [Description("\ue96d")]
    ArrowTurnLeftDown,
    [Description("\ue96e")]
    ArrowTurnLeftUp,
    [Description("\ue96f")]
    ArrowTurnRightDown,
    [Description("\ue970")]
    ArrowTurnRightUp,
    [Description("\ue971")]
    ArrowTurnupLeft,
    [Description("\ue972")]
    ArrowTurnupRight,
    [Description("\ue973")]
    ArrowUp,
    [Description("\ue974")]
    ArrowupArrowDown,
    [Description("\ue975")]
    ArrowupArrowDownCircle,
    [Description("\ue976")]
    ArrowupArrowDownCircleFill,
    [Description("\ue977")]
    ArrowupArrowDownSquare,
    [Description("\ue978")]
    ArrowupArrowDownSquareFill,
    [Description("\ue979")]
    ArrowupBin,
    [Description("\ue97a")]
    ArrowupBinFill,
    [Description("\ue97b")]
    ArrowupCircle,
    [Description("\ue97c")]
    ArrowupCircleFill,
    [Description("\ue97d")]
    ArrowupDoc,
    [Description("\ue97e")]
    ArrowupDocFill,
    [Description("\ue97f")]
    ArrowupDown,
    [Description("\ue980")]
    ArrowupDownCircle,
    [Description("\ue981")]
    ArrowupDownCircleFill,
    [Description("\ue982")]
    ArrowupDownSquare,
    [Description("\ue983")]
    ArrowupDownSquareFill,
    [Description("\ue984")]
    ArrowupLeft,
    [Description("\ue985")]
    ArrowupLeftArrowDownRight,
    [Description("\ue986")]
    ArrowupLeftCircle,
    [Description("\ue987")]
    ArrowupLeftCircleFill,
    [Description("\ue988")]
    ArrowupLeftSquare,
    [Description("\ue989")]
    ArrowupLeftSquareFill,
    [Description("\ue98a")]
    ArrowupRight,
    [Description("\ue98b")]
    ArrowupRightCircle,
    [Description("\ue98c")]
    ArrowupRightCircleFill,
    [Description("\ue98d")]
    ArrowupRightDiamond,
    [Description("\ue98e")]
    ArrowupRightDiamondFill,
    [Description("\ue98f")]
    ArrowupRightSquare,
    [Description("\ue990")]
    ArrowupRightSquareFill,
    [Description("\ue991")]
    ArrowupSquare,
    [Description("\ue992")]
    ArrowupSquareFill,
    [Description("\ue993")]
    ArrowuptoLine,
    [Description("\ue994")]
    ArrowuptoLineAlt,
    [Description("\ue995")]
    ArrowUturnDown,
    [Description("\ue996")]
    ArrowUturnDownCircle,
    [Description("\ue997")]
    ArrowUturnDownCircleFill,
    [Description("\ue998")]
    ArrowUturnDownSquare,
    [Description("\ue999")]
    ArrowUturnDownSquareFill,
    [Description("\ue99a")]
    ArrowUturnLeft,
    [Description("\ue99b")]
    ArrowUturnLeftCircle,
    [Description("\ue99c")]
    ArrowUturnLeftCircleFill,
    [Description("\ue99d")]
    ArrowUturnLeftSquare,
    [Description("\ue99e")]
    ArrowUturnLeftSquareFill,
    [Description("\ue99f")]
    ArrowUturnRight,
    [Description("\ue9a0")]
    ArrowUturnRightCircle,
    [Description("\ue9a1")]
    ArrowUturnRightCircleFill,
    [Description("\ue9a2")]
    ArrowUturnRightSquare,
    [Description("\ue9a3")]
    ArrowUturnRightSquareFill,
    [Description("\ue9a4")]
    ArrowUturnUp,
    [Description("\ue9a5")]
    ArrowUturnupCircle,
    [Description("\ue9a6")]
    ArrowUturnupCircleFill,
    [Description("\ue9a7")]
    ArrowUturnupSquare,
    [Description("\ue9a8")]
    ArrowUturnupSquareFill,
    [Description("\ue9a9")]
    AsteriskCircle,
    [Description("\ue9aa")]
    AsteriskCircleFill,
    [Description("\ue9ab")]
    At,
    [Description("\ue9ac")]
    AtBadgeMinus,
    [Description("\ue9ad")]
    AtBadgePlus,
    [Description("\ue9ae")]
    Backward,
    [Description("\ue9af")]
    BackwardEnd,
    [Description("\ue9b0")]
    BackwardEndAlt,
    [Description("\ue9b1")]
    BackwardEndAltFill,
    [Description("\ue9b2")]
    BackwardEndFill,
    [Description("\ue9b3")]
    BackwardFill,
    [Description("\ue9b4")]
    BadgePlusRadiowavesRight,
    [Description("\ue9b5")]
    Bag,
    [Description("\ue9b6")]
    BagBadgeMinus,
    [Description("\ue9b7")]
    BagBadgePlus,
    [Description("\ue9b8")]
    BagFill,
    [Description("\ue9b9")]
    BagFillBadgeMinus,
    [Description("\ue9ba")]
    BagFillBadgePlus,
    [Description("\ue9bb")]
    Bandage,
    [Description("\ue9bc")]
    BandageFill,
    [Description("\ue9bd")]
    Barcode,
    [Description("\ue9be")]
    BarcodeViewfinder,
    [Description("\ue9bf")]
    Battery0,
    [Description("\ue9c0")]
    Battery25,
    [Description("\ue9c1")]
    Battery100,
    [Description("\ue9c2")]
    BedDouble,
    [Description("\ue9c3")]
    BedDoubleFill,
    [Description("\ue9c4")]
    Bell,
    [Description("\ue9c5")]
    BellCircle,
    [Description("\ue9c6")]
    BellCircleFill,
    [Description("\ue9c7")]
    BellFill,
    [Description("\ue9c8")]
    BellSlash,
    [Description("\ue9c9")]
    BellSlashFill,
    [Description("\ue9ca")]
    BinXmark,
    [Description("\ue9cb")]
    BinXmarkFill,
    [Description("\ue9cc")]
    Bold,
    [Description("\ue9cd")]
    BoldItalicUnderline,
    [Description("\ue9ce")]
    BoldUnderline,
    [Description("\ue9cf")]
    Bolt,
    [Description("\ue9d0")]
    BoltBadgeA,
    [Description("\ue9d1")]
    BoltBadgeaFill,
    [Description("\ue9d2")]
    BoltCircle,
    [Description("\ue9d3")]
    BoltCircleFill,
    [Description("\ue9d4")]
    BoltFill,
    [Description("\ue9d5")]
    BoltHorizontal,
    [Description("\ue9d6")]
    BoltHorizontalCircle,
    [Description("\ue9d7")]
    BoltHorizontalCircleFill,
    [Description("\ue9d8")]
    BoltHorizontalFill,
    [Description("\ue9d9")]
    BoltSlash,
    [Description("\ue9da")]
    BoltSlashFill,
    [Description("\ue9db")]
    Book,
    [Description("\ue9dc")]
    BookCircle,
    [Description("\ue9dd")]
    BookCircleFill,
    [Description("\ue9de")]
    BookFill,
    [Description("\ue9df")]
    Bookmark,
    [Description("\ue9e0")]
    BookmarkFill,
    [Description("\ue9e1")]
    Briefcase,
    [Description("\ue9e2")]
    BriefcaseFill,
    [Description("\ue9e3")]
    BubbleLeft,
    [Description("\ue9e4")]
    BubbleLeftBubbleRight,
    [Description("\ue9e5")]
    BubbleLeftBubbleRightFill,
    [Description("\ue9e6")]
    BubbleLeftFill,
    [Description("\ue9e7")]
    BubbleMiddleBottom,
    [Description("\ue9e8")]
    BubbleMiddleBottomFill,
    [Description("\ue9e9")]
    BubbleMiddleTop,
    [Description("\ue9ea")]
    BubbleMiddleTopFill,
    [Description("\ue9eb")]
    BubbleRight,
    [Description("\ue9ec")]
    BubbleRightFill,
    [Description("\ue9ed")]
    Building,
    [Description("\ue9ee")]
    Building2,
    [Description("\ue9ef")]
    Building2CropCircle,
    [Description("\ue9f0")]
    Building2CropCircleFill,
    [Description("\ue9f1")]
    Building2Fill,
    [Description("\ue9f2")]
    BuildingColumns,
    [Description("\ue9f3")]
    BuildingColumnsFill,
    [Description("\ue9f4")]
    BuildingFill,
    [Description("\ue9f5")]
    Burn,
    [Description("\ue9f6")]
    Burst,
    [Description("\ue9f7")]
    BurstFill,
    [Description("\ue9f8")]
    Calendar,
    [Description("\ue9f9")]
    CalendarBadgeMinus,
    [Description("\ue9fa")]
    CalendarBadgePlus,
    [Description("\ue9fb")]
    CalendarCircle,
    [Description("\ue9fc")]
    CalendarCircleFill,
    [Description("\ue9fd")]
    Camera,
    [Description("\ue9fe")]
    CameraCircle,
    [Description("\ue9ff")]
    CameraCircleFill,
    [Description("\uea00")]
    CameraFill,
    [Description("\uea01")]
    CameraFilters,
    [Description("\uea02")]
    CameraonRectangle,
    [Description("\uea03")]
    CameraonRectangleFill,
    [Description("\uea04")]
    CameraRotate,
    [Description("\uea05")]
    CameraRotateFill,
    [Description("\uea06")]
    CameraViewfinder,
    [Description("\uea07")]
    Capslock,
    [Description("\uea08")]
    CapslockFill,
    [Description("\uea09")]
    Capsule,
    [Description("\uea0a")]
    CapsuleFill,
    [Description("\uea0b")]
    CaptionsBubble,
    [Description("\uea0c")]
    CaptionsBubbleFill,
    [Description("\uea0d")]
    CarFill,
    [Description("\uea0e")]
    Cart,
    [Description("\uea0f")]
    CartBadgeMinus,
    [Description("\uea10")]
    CartBadgePlus,
    [Description("\uea11")]
    CartFill,
    [Description("\uea12")]
    CartFillBadgeMinus,
    [Description("\uea13")]
    CartFillBadgePlus,
    [Description("\uea14")]
    ChartBar,
    [Description("\uea15")]
    ChartBarFill,
    [Description("\uea16")]
    ChartPie,
    [Description("\uea17")]
    ChartPieFill,
    [Description("\uea18")]
    Checkmark,
    [Description("\uea19")]
    CheckmarkCircle,
    [Description("\uea1a")]
    CheckmarkCircleFill,
    [Description("\uea1b")]
    CheckmarkRectangle,
    [Description("\uea1c")]
    CheckmarkRectangleFill,
    [Description("\uea1d")]
    CheckmarkSeal,
    [Description("\uea1e")]
    CheckmarkSealFill,
    [Description("\uea1f")]
    CheckmarkShield,
    [Description("\uea20")]
    CheckmarkShieldFill,
    [Description("\uea21")]
    CheckmarkSquare,
    [Description("\uea22")]
    CheckmarkSquareFill,
    [Description("\uea23")]
    ChevronCompactDown,
    [Description("\uea24")]
    ChevronCompactLeft,
    [Description("\uea25")]
    ChevronCompactRight,
    [Description("\uea26")]
    ChevronCompactUp,
    [Description("\uea27")]
    ChevronDown,
    [Description("\uea28")]
    ChevronDownCircle,
    [Description("\uea29")]
    ChevronDownCircleFill,
    [Description("\uea2a")]
    ChevronDownSquare,
    [Description("\uea2b")]
    ChevronDownSquareFill,
    [Description("\uea2c")]
    ChevronLeft,
    [Description("\uea2d")]
    ChevronLeft2,
    [Description("\uea2e")]
    ChevronLeftCircle,
    [Description("\uea2f")]
    ChevronLeftCircleFill,
    [Description("\uea30")]
    ChevronLeftSlashChevronRight,
    [Description("\uea31")]
    ChevronLeftSquare,
    [Description("\uea32")]
    ChevronLeftSquareFill,
    [Description("\uea33")]
    ChevronRight,
    [Description("\uea34")]
    ChevronRight2,
    [Description("\uea35")]
    ChevronRightCircle,
    [Description("\uea36")]
    ChevronRightCircleFill,
    [Description("\uea37")]
    ChevronRightSquare,
    [Description("\uea38")]
    ChevronRightSquareFill,
    [Description("\uea39")]
    ChevronUp,
    [Description("\uea3a")]
    ChevronupChevronDown,
    [Description("\uea3b")]
    ChevronupCircle,
    [Description("\uea3c")]
    ChevronupCircleFill,
    [Description("\uea3d")]
    ChevronupSquare,
    [Description("\uea3e")]
    ChevronupSquareFill,
    [Description("\uea3f")]
    Circle,
    [Description("\uea40")]
    CircleBottomthirdSplit,
    [Description("\uea41")]
    CircleFill,
    [Description("\uea42")]
    CircleGrid3x3,
    [Description("\uea43")]
    CircleGrid3x3Fill,
    [Description("\uea44")]
    CircleGridHex,
    [Description("\uea45")]
    CircleGridHexFill,
    [Description("\uea46")]
    CircleLefthalfFill,
    [Description("\uea47")]
    CircleRighthalfFill,
    [Description("\uea48")]
    Clear,
    [Description("\uea49")]
    ClearFill,
    [Description("\uea4a")]
    Clock,
    [Description("\uea4b")]
    ClockFill,
    [Description("\uea4c")]
    Cloud,
    [Description("\uea4d")]
    CloudBolt,
    [Description("\uea4e")]
    CloudBoltFill,
    [Description("\uea4f")]
    CloudBoltRain,
    [Description("\uea50")]
    CloudBoltRainFill,
    [Description("\uea51")]
    CloudDrizzle,
    [Description("\uea52")]
    CloudDrizzleFill,
    [Description("\uea53")]
    CloudFill,
    [Description("\uea54")]
    CloudFog,
    [Description("\uea55")]
    CloudFogFill,
    [Description("\uea56")]
    CloudHail,
    [Description("\uea57")]
    CloudHailFill,
    [Description("\uea58")]
    CloudHeavyrain,
    [Description("\uea59")]
    CloudHeavyrainFill,
    [Description("\uea5a")]
    CloudMoon,
    [Description("\uea5b")]
    CloudMoonBolt,
    [Description("\uea5c")]
    CloudMoonBoltFill,
    [Description("\uea5d")]
    CloudMoonFill,
    [Description("\uea5e")]
    CloudMoonRain,
    [Description("\uea5f")]
    CloudMoonRainFill,
    [Description("\uea60")]
    CloudRain,
    [Description("\uea61")]
    CloudRainFill,
    [Description("\uea62")]
    CloudSleet,
    [Description("\uea63")]
    CloudSleetFill,
    [Description("\uea64")]
    CloudSnow,
    [Description("\uea65")]
    CloudSnowFill,
    [Description("\uea66")]
    CloudSun,
    [Description("\uea67")]
    CloudSunBolt,
    [Description("\uea68")]
    CloudSunBoltFill,
    [Description("\uea69")]
    CloudSunFill,
    [Description("\uea6a")]
    CloudSunRain,
    [Description("\uea6b")]
    CloudSunRainFill,
    [Description("\uea6c")]
    Command,
    [Description("\uea6d")]
    Control,
    [Description("\uea6e")]
    Creditcard,
    [Description("\uea6f")]
    CreditcardFill,
    [Description("\uea70")]
    Crop,
    [Description("\uea71")]
    CropRotate,
    [Description("\uea72")]
    Cube,
    [Description("\uea73")]
    CubeBox,
    [Description("\uea74")]
    CubeBoxFill,
    [Description("\uea75")]
    CubeFill,
    [Description("\uea76")]
    CursorRays,
    [Description("\uea77")]
    DecreaseIndent,
    [Description("\uea78")]
    DecreaseQuotelevel,
    [Description("\uea79")]
    DeleteLeft,
    [Description("\uea7a")]
    DeleteLeftFill,
    [Description("\uea7b")]
    DeleteRight,
    [Description("\uea7c")]
    DeleteRightFill,
    [Description("\uea7d")]
    Desktopcomputer,
    [Description("\uea7e")]
    Dial,
    [Description("\uea7f")]
    DialFill,
    [Description("\uea80")]
    Divide,
    [Description("\uea81")]
    DivideCircle,
    [Description("\uea82")]
    DivideCircleFill,
    [Description("\uea83")]
    DivideSquare,
    [Description("\uea84")]
    DivideSquareFill,
    [Description("\uea85")]
    Doc,
    [Description("\uea86")]
    DocAppend,
    [Description("\uea87")]
    DocCircle,
    [Description("\uea88")]
    DocCircleFill,
    [Description("\uea89")]
    DocFill,
    [Description("\uea8a")]
    DoconClipboard,
    [Description("\uea8b")]
    DoconClipboardFill,
    [Description("\uea8c")]
    DoconDoc,
    [Description("\uea8d")]
    DoconDocFill,
    [Description("\uea8e")]
    DocPlaintext,
    [Description("\uea8f")]
    DocRichtext,
    [Description("\uea90")]
    DocText,
    [Description("\uea91")]
    DocTextFill,
    [Description("\uea92")]
    DocTextSearch,
    [Description("\uea93")]
    DocTextViewfinder,
    [Description("\uea94")]
    DotRadiowavesLeftRight,
    [Description("\uea95")]
    DotRadiowavesRight,
    [Description("\uea96")]
    DotSquare,
    [Description("\uea97")]
    DotSquareFill,
    [Description("\uea98")]
    DropTriangle,
    [Description("\uea99")]
    DropTriangleFill,
    [Description("\uea9a")]
    Ear,
    [Description("\uea9b")]
    Eject,
    [Description("\uea9c")]
    EjectFill,
    [Description("\uea9d")]
    EllipsesBubble,
    [Description("\uea9e")]
    EllipsesBubbleFill,
    [Description("\uea9f")]
    Ellipsis,
    [Description("\ueaa0")]
    EllipsisCircle,
    [Description("\ueaa1")]
    EllipsisCircleFill,
    [Description("\ueaa2")]
    Envelope,
    [Description("\ueaa3")]
    EnvelopeBadge,
    [Description("\ueaa4")]
    EnvelopeBadgeFill,
    [Description("\ueaa5")]
    EnvelopeCircle,
    [Description("\ueaa6")]
    EnvelopeCircleFill,
    [Description("\ueaa7")]
    EnvelopeFill,
    [Description("\ueaa8")]
    EnvelopeOpen,
    [Description("\ueaa9")]
    EnvelopeOpenFill,
    [Description("\ueaaa")]
    Equal,
    [Description("\ueaab")]
    EqualCircle,
    [Description("\ueaac")]
    EqualCircleFill,
    [Description("\ueaad")]
    EqualSquare,
    [Description("\ueaae")]
    EqualSquareFill,
    [Description("\ueaaf")]
    Escape,
    [Description("\ueab0")]
    Exclamationmark,
    [Description("\ueab1")]
    ExclamationmarkBubble,
    [Description("\ueab2")]
    ExclamationmarkBubbleFill,
    [Description("\ueab3")]
    ExclamationmarkCircle,
    [Description("\ueab4")]
    ExclamationmarkCircleFill,
    [Description("\ueab5")]
    ExclamationmarkOctagon,
    [Description("\ueab6")]
    ExclamationmarkOctagonFill,
    [Description("\ueab7")]
    ExclamationmarkShield,
    [Description("\ueab8")]
    ExclamationmarkShieldFill,
    [Description("\ueab9")]
    ExclamationmarkSquare,
    [Description("\ueaba")]
    ExclamationmarkSquareFill,
    [Description("\ueabb")]
    ExclamationmarkTriangle,
    [Description("\ueabc")]
    ExclamationmarkTriangleFill,
    [Description("\ueabd")]
    Eye,
    [Description("\ueabe")]
    Eyedropper,
    [Description("\ueabf")]
    EyedropperFull,
    [Description("\ueac0")]
    EyedropperHalffull,
    [Description("\ueac1")]
    EyeFill,
    [Description("\ueac2")]
    Eyeglasses,
    [Description("\ueac3")]
    EyeSlash,
    [Description("\ueac4")]
    EyeSlashFill,
    [Description("\ueac5")]
    Facemask,
    [Description("\ueac6")]
    FacemaskFill,
    [Description("\ueac7")]
    FaceSmiling,
    [Description("\ueac8")]
    FaceSmilingFill,
    [Description("\ueac9")]
    FCursive,
    [Description("\ueaca")]
    FCursiveCircle,
    [Description("\ueacb")]
    FCursiveCircleFill,
    [Description("\ueacc")]
    Film,
    [Description("\ueacd")]
    FilmFill,
    [Description("\ueace")]
    Flag,
    [Description("\ueacf")]
    FlagCircle,
    [Description("\uead0")]
    FlagCircleFill,
    [Description("\uead1")]
    FlagFill,
    [Description("\uead2")]
    FlagSlash,
    [Description("\uead3")]
    FlagSlashFill,
    [Description("\uead4")]
    Flame,
    [Description("\uead5")]
    FlameFill,
    [Description("\uead6")]
    Flowchart,
    [Description("\uead7")]
    FlowchartFill,
    [Description("\uead8")]
    Folder,
    [Description("\uead9")]
    FolderBadgeMinus,
    [Description("\ueada")]
    FolderBadgePersonCrop,
    [Description("\ueadb")]
    FolderBadgePlus,
    [Description("\ueadc")]
    FolderCircle,
    [Description("\ueadd")]
    FolderCircleFill,
    [Description("\ueade")]
    FolderFill,
    [Description("\ueadf")]
    FolderFillBadgeMinus,
    [Description("\ueae0")]
    FolderFillBadgePersonCrop,
    [Description("\ueae1")]
    FolderFillBadgePlus,
    [Description("\ueae2")]
    Forward,
    [Description("\ueae3")]
    ForwardEnd,
    [Description("\ueae4")]
    ForwardEndAlt,
    [Description("\ueae5")]
    ForwardEndAltFill,
    [Description("\ueae6")]
    ForwardEndFill,
    [Description("\ueae7")]
    ForwardFill,
    [Description("\ueae8")]
    Function,
    [Description("\ueae9")]
    Fx,
    [Description("\ueaea")]
    Gamecontroller,
    [Description("\ueaeb")]
    GamecontrollerFill,
    [Description("\ueaec")]
    Gauge,
    [Description("\ueaed")]
    GaugeBadgeMinus,
    [Description("\ueaee")]
    GaugeBadgePlus,
    [Description("\ueaef")]
    Gear,
    [Description("\ueaf0")]
    Gift,
    [Description("\ueaf1")]
    GiftAlt,
    [Description("\ueaf2")]
    GiftAltFill,
    [Description("\ueaf3")]
    Giftcard,
    [Description("\ueaf4")]
    GiftcardFill,
    [Description("\ueaf5")]
    GiftFill,
    [Description("\ueaf6")]
    Globe,
    [Description("\ueaf7")]
    Gobackward,
    [Description("\ueaf8")]
    Gobackward10,
    [Description("\ueaf9")]
    Gobackward15,
    [Description("\ueafa")]
    Gobackward30,
    [Description("\ueafb")]
    Gobackward45,
    [Description("\ueafc")]
    Gobackward60,
    [Description("\ueafd")]
    Gobackward75,
    [Description("\ueafe")]
    Gobackward90,
    [Description("\ueaff")]
    GobackwardMinus,
    [Description("\ueb00")]
    Goforward,
    [Description("\ueb01")]
    Goforward10,
    [Description("\ueb02")]
    Goforward15,
    [Description("\ueb03")]
    Goforward30,
    [Description("\ueb04")]
    Goforward45,
    [Description("\ueb05")]
    Goforward60,
    [Description("\ueb06")]
    Goforward75,
    [Description("\ueb07")]
    Goforward90,
    [Description("\ueb08")]
    GoforwardPlus,
    [Description("\ueb09")]
    Greaterthan,
    [Description("\ueb0a")]
    GreaterthanCircle,
    [Description("\ueb0b")]
    GreaterthanCircleFill,
    [Description("\ueb0c")]
    GreaterthanSquare,
    [Description("\ueb0d")]
    GreaterthanSquareFill,
    [Description("\ueb0e")]
    Grid,
    [Description("\ueb0f")]
    GridCircle,
    [Description("\ueb10")]
    GridCircleFill,
    [Description("\ueb11")]
    Guitars,
    [Description("\ueb12")]
    Hammer,
    [Description("\ueb13")]
    HammerFill,
    [Description("\ueb14")]
    HandDraw,
    [Description("\ueb15")]
    HandDrawFill,
    [Description("\ueb16")]
    HandPointLeft,
    [Description("\ueb17")]
    HandPointLeftFill,
    [Description("\ueb18")]
    HandPointRight,
    [Description("\ueb19")]
    HandPointRightFill,
    [Description("\ueb1a")]
    HandRaised,
    [Description("\ueb1b")]
    HandRaisedFill,
    [Description("\ueb1c")]
    HandRaisedSlash,
    [Description("\ueb1d")]
    HandRaisedSlashFill,
    [Description("\ueb1e")]
    HandThumbsdown,
    [Description("\ueb1f")]
    HandThumbsdownFill,
    [Description("\ueb20")]
    HandThumbsup,
    [Description("\ueb21")]
    HandThumbsupFill,
    [Description("\ueb22")]
    Hare,
    [Description("\ueb23")]
    HareFill,
    [Description("\ueb24")]
    Headphones,
    [Description("\ueb25")]
    Heart,
    [Description("\ueb26")]
    HeartCircle,
    [Description("\ueb27")]
    HeartCircleFill,
    [Description("\ueb28")]
    HeartFill,
    [Description("\ueb29")]
    HeartSlash,
    [Description("\ueb2a")]
    HeartSlashCircle,
    [Description("\ueb2b")]
    HeartSlashCircleFill,
    [Description("\ueb2c")]
    HeartSlashFill,
    [Description("\ueb2d")]
    Helm,
    [Description("\ueb2e")]
    Hexagon,
    [Description("\ueb2f")]
    HexagonFill,
    [Description("\ueb30")]
    Hifispeaker,
    [Description("\ueb31")]
    HifispeakerFill,
    [Description("\ueb32")]
    Hourglass,
    [Description("\ueb33")]
    HourglassBottomhalfFill,
    [Description("\ueb34")]
    HourglassTophalfFill,
    [Description("\ueb35")]
    House,
    [Description("\ueb36")]
    HouseFill,
    [Description("\ueb37")]
    Hurricane,
    [Description("\ueb38")]
    IncreaseIndent,
    [Description("\ueb39")]
    IncreaseQuotelevel,
    [Description("\ueb3a")]
    Info,
    [Description("\ueb3b")]
    InfoCircle,
    [Description("\ueb3c")]
    InfoCircleFill,
    [Description("\ueb3d")]
    Italic,
    [Description("\ueb3e")]
    Keyboard,
    [Description("\ueb3f")]
    KeyboardChevronCompactDown,
    [Description("\ueb40")]
    LargecircleFillCircle,
    [Description("\ueb41")]
    Lasso,
    [Description("\ueb42")]
    LeafArrowCirclepath,
    [Description("\ueb43")]
    Lessthan,
    [Description("\ueb44")]
    LessthanCircle,
    [Description("\ueb45")]
    LessthanCircleFill,
    [Description("\ueb46")]
    LessthanSquare,
    [Description("\ueb47")]
    LessthanSquareFill,
    [Description("\ueb48")]
    Lightbulb,
    [Description("\ueb49")]
    LightbulbFill,
    [Description("\ueb4a")]
    LightbulbSlash,
    [Description("\ueb4b")]
    LightbulbSlashFill,
    [Description("\ueb4c")]
    LightMax,
    [Description("\ueb4d")]
    LightMin,
    [Description("\ueb4e")]
    LineHorizontal3,
    [Description("\ueb4f")]
    LineHorizontal3Decrease,
    [Description("\ueb50")]
    LineHorizontal3DecreaseCircle,
    [Description("\ueb51")]
    LineHorizontal3DecreaseCircleFill,
    [Description("\ueb52")]
    Link,
    [Description("\ueb53")]
    LinkCircle,
    [Description("\ueb54")]
    LinkCircleFill,
    [Description("\ueb55")]
    ListBullet,
    [Description("\ueb56")]
    ListBulletBelowRectangle,
    [Description("\ueb57")]
    ListBulletIndent,
    [Description("\ueb58")]
    ListDash,
    [Description("\ueb59")]
    ListNumber,
    [Description("\ueb5a")]
    ListNumberRtl,
    [Description("\ueb5b")]
    Location,
    [Description("\ueb5c")]
    LocationCircle,
    [Description("\ueb5d")]
    LocationCircleFill,
    [Description("\ueb5e")]
    LocationFill,
    [Description("\ueb5f")]
    LocationNorth,
    [Description("\ueb60")]
    LocationNorthFill,
    [Description("\ueb61")]
    LocationNorthLine,
    [Description("\ueb62")]
    LocationNorthLineFill,
    [Description("\ueb63")]
    LocationSlash,
    [Description("\ueb64")]
    LocationSlashFill,
    [Description("\ueb65")]
    Lock,
    [Description("\ueb66")]
    LockCircle,
    [Description("\ueb67")]
    LockCircleFill,
    [Description("\ueb68")]
    LockFill,
    [Description("\ueb69")]
    LockOpen,
    [Description("\ueb6a")]
    LockOpenFill,
    [Description("\ueb6b")]
    LockRotation,
    [Description("\ueb6c")]
    LockRotationOpen,
    [Description("\ueb6d")]
    LockShield,
    [Description("\ueb6e")]
    LockShieldFill,
    [Description("\ueb6f")]
    LockSlash,
    [Description("\ueb70")]
    LockSlashFill,
    [Description("\ueb71")]
    Macwindow,
    [Description("\ueb72")]
    Map,
    [Description("\ueb73")]
    MapFill,
    [Description("\ueb74")]
    MapPin,
    [Description("\ueb75")]
    MapPinEllipse,
    [Description("\ueb76")]
    MapPinSlash,
    [Description("\ueb77")]
    Memories,
    [Description("\ueb78")]
    MemoriesBadgeMinus,
    [Description("\ueb79")]
    MemoriesBadgePlus,
    [Description("\ueb7a")]
    Metronome,
    [Description("\ueb7b")]
    Mic,
    [Description("\ueb7c")]
    MicCircle,
    [Description("\ueb7d")]
    MicCircleFill,
    [Description("\ueb7e")]
    MicFill,
    [Description("\ueb7f")]
    MicSlash,
    [Description("\ueb80")]
    MicSlashFill,
    [Description("\ueb81")]
    Minus,
    [Description("\ueb82")]
    MinusCircle,
    [Description("\ueb83")]
    MinusCircleFill,
    [Description("\ueb84")]
    MinusRectangle,
    [Description("\ueb85")]
    MinusRectangleFill,
    [Description("\ueb86")]
    MinusSlashPlus,
    [Description("\ueb87")]
    MinusSquare,
    [Description("\ueb88")]
    MinusSquareFill,
    [Description("\ueb89")]
    Moon,
    [Description("\ueb8a")]
    MoonCircle,
    [Description("\ueb8b")]
    MoonCircleFill,
    [Description("\ueb8c")]
    MoonFill,
    [Description("\ueb8d")]
    MoonStars,
    [Description("\ueb8e")]
    MoonStarsFill,
    [Description("\ueb8f")]
    MoonZzz,
    [Description("\ueb90")]
    MoonZzzFill,
    [Description("\ueb91")]
    Multiply,
    [Description("\ueb92")]
    MultiplyCircle,
    [Description("\ueb93")]
    MultiplyCircleFill,
    [Description("\ueb94")]
    MultiplySquare,
    [Description("\ueb95")]
    MultiplySquareFill,
    [Description("\ueb96")]
    MusicHouse,
    [Description("\ueb97")]
    MusicHouseFill,
    [Description("\ueb98")]
    MusicMic,
    [Description("\ueb99")]
    MusicNote,
    [Description("\ueb9a")]
    MusicNoteList,
    [Description("\ueb9b")]
    Nosign,
    [Description("\ueb9c")]
    Number,
    [Description("\ueb9d")]
    NumberCircle,
    [Description("\ueb9e")]
    NumberCircleFill,
    [Description("\ueb9f")]
    NumberSquare,
    [Description("\ueba0")]
    NumberSquareFill,
    [Description("\ueba1")]
    Option,
    [Description("\ueba2")]
    Paintbrush,
    [Description("\ueba3")]
    PaintbrushFill,
    [Description("\ueba4")]
    Pano,
    [Description("\ueba5")]
    PanoFill,
    [Description("\ueba6")]
    Paperclip,
    [Description("\ueba7")]
    Paperplane,
    [Description("\ueba8")]
    PaperplaneFill,
    [Description("\ueba9")]
    Paragraph,
    [Description("\uebaa")]
    Pause,
    [Description("\uebab")]
    PauseCircle,
    [Description("\uebac")]
    PauseCircleFill,
    [Description("\uebad")]
    PauseFill,
    [Description("\uebae")]
    PauseRectangle,
    [Description("\uebaf")]
    PauseRectangleFill,
    [Description("\uebb0")]
    Pencil,
    [Description("\uebb1")]
    PencilCircle,
    [Description("\uebb2")]
    PencilCircleFill,
    [Description("\uebb3")]
    PencilEllipsisRectangle,
    [Description("\uebb4")]
    PencilOutline,
    [Description("\uebb5")]
    PencilSlash,
    [Description("\uebb6")]
    Percent,
    [Description("\uebb7")]
    Person,
    [Description("\uebb8")]
    Person2,
    [Description("\uebb9")]
    Person2Fill,
    [Description("\uebba")]
    Person2SquareStack,
    [Description("\uebbb")]
    Person2SquareStackFill,
    [Description("\uebbc")]
    Person3,
    [Description("\uebbd")]
    Person3Fill,
    [Description("\uebbe")]
    Personalhotspot,
    [Description("\uebbf")]
    PersonBadgeMinus,
    [Description("\uebc0")]
    PersonBadgeMinusFill,
    [Description("\uebc1")]
    PersonBadgePlus,
    [Description("\uebc2")]
    PersonBadgePlusFill,
    [Description("\uebc3")]
    PersonCircle,
    [Description("\uebc4")]
    PersonCircleFill,
    [Description("\uebc5")]
    PersonCropCircle,
    [Description("\uebc6")]
    PersonCropCircleBadgeCheckmark,
    [Description("\uebc7")]
    PersonCropCircleBadgeExclam,
    [Description("\uebc8")]
    PersonCropCircleBadgeMinus,
    [Description("\uebc9")]
    PersonCropCircleBadgePlus,
    [Description("\uebca")]
    PersonCropCircleBadgeXmark,
    [Description("\uebcb")]
    PersonCropCircleFill,
    [Description("\uebcc")]
    PersonCropCircleFillBadgeCheckmark,
    [Description("\uebcd")]
    PersonCropCircleFillBadgeExclam,
    [Description("\uebce")]
    PersonCropCircleFillBadgeMinus,
    [Description("\uebcf")]
    PersonCropCircleFillBadgePlus,
    [Description("\uebd0")]
    PersonCropCircleFillBadgeXmark,
    [Description("\uebd1")]
    PersonCropRectangle,
    [Description("\uebd2")]
    PersonCropRectangleFill,
    [Description("\uebd3")]
    PersonCropSquare,
    [Description("\uebd4")]
    PersonCropSquareFill,
    [Description("\uebd5")]
    PersonFill,
    [Description("\uebd6")]
    Perspective,
    [Description("\uebd7")]
    Phone,
    [Description("\uebd8")]
    PhoneArrowDownLeft,
    [Description("\uebd9")]
    PhoneArrowRight,
    [Description("\uebda")]
    PhoneArrowupRight,
    [Description("\uebdb")]
    PhoneBadgePlus,
    [Description("\uebdc")]
    PhoneCircle,
    [Description("\uebdd")]
    PhoneCircleFill,
    [Description("\uebde")]
    PhoneDown,
    [Description("\uebdf")]
    PhoneDownCircle,
    [Description("\uebe0")]
    PhoneDownCircleFill,
    [Description("\uebe1")]
    PhoneDownFill,
    [Description("\uebe2")]
    PhoneFill,
    [Description("\uebe3")]
    PhoneFillArrowDownLeft,
    [Description("\uebe4")]
    PhoneFillArrowRight,
    [Description("\uebe5")]
    PhoneFillArrowupRight,
    [Description("\uebe6")]
    PhoneFillBadgePlus,
    [Description("\uebe7")]
    Photo,
    [Description("\uebe8")]
    PhotoFill,
    [Description("\uebe9")]
    PhotoFillonRectangleFill,
    [Description("\uebea")]
    PhotoonRectangle,
    [Description("\uebeb")]
    Pin,
    [Description("\uebec")]
    PinFill,
    [Description("\uebed")]
    PinSlash,
    [Description("\uebee")]
    PinSlashFill,
    [Description("\uebef")]
    Play,
    [Description("\uebf0")]
    PlayCircle,
    [Description("\uebf1")]
    PlayCircleFill,
    [Description("\uebf2")]
    PlayFill,
    [Description("\uebf3")]
    Playpause,
    [Description("\uebf4")]
    PlaypauseFill,
    [Description("\uebf5")]
    PlayRectangle,
    [Description("\uebf6")]
    PlayRectangleFill,
    [Description("\uebf7")]
    Plus,
    [Description("\uebf8")]
    PlusApp,
    [Description("\uebf9")]
    PlusAppFill,
    [Description("\uebfa")]
    PlusBubble,
    [Description("\uebfb")]
    PlusBubbleFill,
    [Description("\uebfc")]
    PlusCircle,
    [Description("\uebfd")]
    PlusCircleFill,
    [Description("\uebfe")]
    Plusminus,
    [Description("\uebff")]
    PlusminusCircle,
    [Description("\uec00")]
    PlusminusCircleFill,
    [Description("\uec01")]
    PlusRectangle,
    [Description("\uec02")]
    PlusRectangleFill,
    [Description("\uec03")]
    PlusRectangleFillonRectangleFill,
    [Description("\uec04")]
    PlusRectangleonRectangle,
    [Description("\uec05")]
    PlusSlashMinus,
    [Description("\uec06")]
    PlusSquare,
    [Description("\uec07")]
    PlusSquareFill,
    [Description("\uec08")]
    PlusSquareFillonSquareFill,
    [Description("\uec09")]
    PlusSquareonSquare,
    [Description("\uec0a")]
    Power,
    [Description("\uec0b")]
    Printer,
    [Description("\uec0c")]
    PrinterFill,
    [Description("\uec0d")]
    Projective,
    [Description("\uec0e")]
    Purchased,
    [Description("\uec0f")]
    PurchasedCircle,
    [Description("\uec10")]
    PurchasedCircleFill,
    [Description("\uec11")]
    Qrcode,
    [Description("\uec12")]
    QrcodeViewfinder,
    [Description("\uec13")]
    Question,
    [Description("\uec14")]
    QuestionCircle,
    [Description("\uec15")]
    QuestionCircleFill,
    [Description("\uec16")]
    QuestionDiamond,
    [Description("\uec17")]
    QuestionDiamondFill,
    [Description("\uec18")]
    QuestionSquare,
    [Description("\uec19")]
    QuestionSquareFill,
    [Description("\uec1a")]
    QuoteBubble,
    [Description("\uec1b")]
    QuoteBubbleFill,
    [Description("\uec1c")]
    RadiowavesLeft,
    [Description("\uec1d")]
    RadiowavesRight,
    [Description("\uec1e")]
    Rays,
    [Description("\uec1f")]
    Recordingtape,
    [Description("\uec20")]
    Rectangle,
    [Description("\uec21")]
    Rectangle3Offgrid,
    [Description("\uec22")]
    Rectangle3OffgridFill,
    [Description("\uec23")]
    RectangleArrowupRightArrowDownLeft,
    [Description("\uec24")]
    RectangleArrowupRightArrowDownLeftSlash,
    [Description("\uec25")]
    RectangleBadgeCheckmark,
    [Description("\uec26")]
    RectangleBadgeXmark,
    [Description("\uec27")]
    RectangleCompressVertical,
    [Description("\uec28")]
    RectangleDock,
    [Description("\uec29")]
    RectangleExpandVertical,
    [Description("\uec2a")]
    RectangleFill,
    [Description("\uec2b")]
    RectangleFillBadgeCheckmark,
    [Description("\uec2c")]
    RectangleFillBadgeXmark,
    [Description("\uec2d")]
    RectangleFillonRectangleAngledFill,
    [Description("\uec2e")]
    RectangleFillonRectangleFill,
    [Description("\uec2f")]
    RectangleGrid1x2,
    [Description("\uec30")]
    RectangleGrid1x2Fill,
    [Description("\uec31")]
    RectangleGrid2x2,
    [Description("\uec32")]
    RectangleGrid2x2Fill,
    [Description("\uec33")]
    RectangleGrid3x2,
    [Description("\uec34")]
    RectangleGrid3x2Fill,
    [Description("\uec35")]
    RectangleonRectangle,
    [Description("\uec36")]
    RectangleonRectangleAngled,
    [Description("\uec37")]
    RectanglePaperclip,
    [Description("\uec38")]
    RectangleSplit3x1,
    [Description("\uec39")]
    RectangleSplit3x1Fill,
    [Description("\uec3a")]
    RectangleSplit3x3,
    [Description("\uec3b")]
    RectangleSplit3x3Fill,
    [Description("\uec3c")]
    RectangleStack,
    [Description("\uec3d")]
    RectangleStackBadgeMinus,
    [Description("\uec3e")]
    RectangleStackBadgePersonCrop,
    [Description("\uec3f")]
    RectangleStackBadgePlus,
    [Description("\uec40")]
    RectangleStackFill,
    [Description("\uec41")]
    RectangleStackFillBadgeMinus,
    [Description("\uec42")]
    RectangleStackFillBadgePersonCrop,
    [Description("\uec43")]
    RectangleStackFillBadgePlus,
    [Description("\uec44")]
    RectangleStackPersonCrop,
    [Description("\uec45")]
    RectangleStackPersonCropFill,
    [Description("\uec46")]
    Repeat,
    [Description("\uec47")]
    Repeat1,
    [Description("\uec48")]
    Return,
    [Description("\uec49")]
    Rhombus,
    [Description("\uec4a")]
    RhombusFill,
    [Description("\uec4b")]
    Rosette,
    [Description("\uec4c")]
    RotateLeft,
    [Description("\uec4d")]
    RotateLeftFill,
    [Description("\uec4e")]
    RotateRight,
    [Description("\uec4f")]
    RotateRightFill,
    [Description("\uec50")]
    Scissors,
    [Description("\uec51")]
    Scope,
    [Description("\uec52")]
    Scribble,
    [Description("\uec53")]
    Search,
    [Description("\uec54")]
    SearchCircle,
    [Description("\uec55")]
    SearchCircleFill,
    [Description("\uec56")]
    SelectionPininOut,
    [Description("\uec57")]
    Shield,
    [Description("\uec58")]
    ShieldFill,
    [Description("\uec59")]
    ShieldLefthalfFill,
    [Description("\uec5a")]
    ShieldSlash,
    [Description("\uec5b")]
    ShieldSlashFill,
    [Description("\uec5c")]
    Shift,
    [Description("\uec5d")]
    ShiftFill,
    [Description("\uec5e")]
    Shippingbox,
    [Description("\uec5f")]
    ShippingboxFill,
    [Description("\uec60")]
    Shuffle,
    [Description("\uec61")]
    SidebarLeft,
    [Description("\uec62")]
    SidebarRight,
    [Description("\uec63")]
    Signature,
    [Description("\uec64")]
    Skew,
    [Description("\uec65")]
    SlashCircle,
    [Description("\uec66")]
    SlashCircleFill,
    [Description("\uec67")]
    SliderHorizontal3,
    [Description("\uec68")]
    SliderHorizontalBelowRectangle,
    [Description("\uec69")]
    Slowmo,
    [Description("\uec6a")]
    SmallcircleCircle,
    [Description("\uec6b")]
    SmallcircleCircleFill,
    [Description("\uec6c")]
    SmallcircleFillCircle,
    [Description("\uec6d")]
    SmallcircleFillCircleFill,
    [Description("\uec6e")]
    Smiley,
    [Description("\uec6f")]
    SmileyFill,
    [Description("\uec70")]
    Smoke,
    [Description("\uec71")]
    SmokeFill,
    [Description("\uec72")]
    Snow,
    [Description("\uec73")]
    Sparkles,
    [Description("\uec74")]
    Speaker,
    [Description("\uec75")]
    Speaker1,
    [Description("\uec76")]
    Speaker1Fill,
    [Description("\uec77")]
    Speaker2,
    [Description("\uec78")]
    Speaker2Fill,
    [Description("\uec79")]
    Speaker3,
    [Description("\uec7a")]
    Speaker3Fill,
    [Description("\uec7b")]
    SpeakerFill,
    [Description("\uec7c")]
    SpeakerSlash,
    [Description("\uec7d")]
    SpeakerSlashFill,
    [Description("\uec7e")]
    SpeakerSlashFillRtl,
    [Description("\uec7f")]
    SpeakerSlashRtl,
    [Description("\uec80")]
    SpeakerZzz,
    [Description("\uec81")]
    SpeakerZzzFill,
    [Description("\uec82")]
    SpeakerZzzFillRtl,
    [Description("\uec83")]
    SpeakerZzzRtl,
    [Description("\uec84")]
    Speedometer,
    [Description("\uec85")]
    Sportscourt,
    [Description("\uec86")]
    SportscourtFill,
    [Description("\uec87")]
    Square,
    [Description("\uec88")]
    SquareArrowDown,
    [Description("\uec89")]
    SquareArrowDownFill,
    [Description("\uec8a")]
    SquareArrowDownonSquare,
    [Description("\uec8b")]
    SquareArrowDownonSquareFill,
    [Description("\uec8c")]
    SquareArrowUp,
    [Description("\uec8d")]
    SquareArrowupFill,
    [Description("\uec8e")]
    SquareArrowuponSquare,
    [Description("\uec8f")]
    SquareArrowuponSquareFill,
    [Description("\uec90")]
    SquareFill,
    [Description("\uec91")]
    SquareFillLineVerticalSquare,
    [Description("\uec92")]
    SquareFillLineVerticalSquareFill,
    [Description("\uec93")]
    SquareFillonCircleFill,
    [Description("\uec94")]
    SquareFillonSquareFill,
    [Description("\uec95")]
    SquareGrid2x2,
    [Description("\uec96")]
    SquareGrid2x2Fill,
    [Description("\uec97")]
    SquareGrid3x2,
    [Description("\uec98")]
    SquareGrid3x2Fill,
    [Description("\uec99")]
    SquareGrid4x3Fill,
    [Description("\uec9a")]
    SquareLefthalfFill,
    [Description("\uec9b")]
    SquareLineVerticalSquare,
    [Description("\uec9c")]
    SquareLineVerticalSquareFill,
    [Description("\uec9d")]
    SquareonCircle,
    [Description("\uec9e")]
    SquareonSquare,
    [Description("\uec9f")]
    SquarePencil,
    [Description("\ueca0")]
    SquareRighthalfFill,
    [Description("\ueca1")]
    SquaresBelowRectangle,
    [Description("\ueca2")]
    SquareSplit1x2,
    [Description("\ueca3")]
    SquareSplit1x2Fill,
    [Description("\ueca4")]
    SquareSplit2x1,
    [Description("\ueca5")]
    SquareSplit2x1Fill,
    [Description("\ueca6")]
    SquareSplit2x2,
    [Description("\ueca7")]
    SquareSplit2x2Fill,
    [Description("\ueca8")]
    SquareStack,
    [Description("\ueca9")]
    SquareStack3dDownDottedline,
    [Description("\uecaa")]
    SquareStack3dDownRight,
    [Description("\uecab")]
    SquareStack3dDownRightFill,
    [Description("\uecac")]
    SquareStack3dUp,
    [Description("\uecad")]
    SquareStack3dupFill,
    [Description("\uecae")]
    SquareStack3dupSlash,
    [Description("\uecaf")]
    SquareStack3dupSlashFill,
    [Description("\uecb0")]
    SquareStackFill,
    [Description("\uecb1")]
    Star,
    [Description("\uecb2")]
    StarCircle,
    [Description("\uecb3")]
    StarCircleFill,
    [Description("\uecb4")]
    StarFill,
    [Description("\uecb5")]
    StarLefthalfFill,
    [Description("\uecb6")]
    Staroflife,
    [Description("\uecb7")]
    StaroflifeFill,
    [Description("\uecb8")]
    StarSlash,
    [Description("\uecb9")]
    StarSlashFill,
    [Description("\uecba")]
    Stop,
    [Description("\uecbb")]
    StopCircle,
    [Description("\uecbc")]
    StopCircleFill,
    [Description("\uecbd")]
    StopFill,
    [Description("\uecbe")]
    Stopwatch,
    [Description("\uecbf")]
    StopwatchFill,
    [Description("\uecc0")]
    Strikethrough,
    [Description("\uecc1")]
    SuitClub,
    [Description("\uecc2")]
    SuitClubFill,
    [Description("\uecc3")]
    SuitDiamond,
    [Description("\uecc4")]
    SuitDiamondFill,
    [Description("\uecc5")]
    SuitHeart,
    [Description("\uecc6")]
    SuitHeartFill,
    [Description("\uecc7")]
    SuitSpade,
    [Description("\uecc8")]
    SuitSpadeFill,
    [Description("\uecc9")]
    Sum,
    [Description("\uecca")]
    SunDust,
    [Description("\ueccb")]
    SunDustFill,
    [Description("\ueccc")]
    SunHaze,
    [Description("\ueccd")]
    SunHazeFill,
    [Description("\uecce")]
    SunMax,
    [Description("\ueccf")]
    SunMaxFill,
    [Description("\uecd0")]
    SunMin,
    [Description("\uecd1")]
    SunMinFill,
    [Description("\uecd2")]
    Sunrise,
    [Description("\uecd3")]
    SunriseFill,
    [Description("\uecd4")]
    Sunset,
    [Description("\uecd5")]
    SunsetFill,
    [Description("\uecd6")]
    Table,
    [Description("\uecd7")]
    TableBadgeMore,
    [Description("\uecd8")]
    TableBadgeMoreFill,
    [Description("\uecd9")]
    TableFill,
    [Description("\uecda")]
    Tag,
    [Description("\uecdb")]
    TagCircle,
    [Description("\uecdc")]
    TagCircleFill,
    [Description("\uecdd")]
    TagFill,
    [Description("\uecde")]
    TBubble,
    [Description("\uecdf")]
    TBubbleFill,
    [Description("\uece0")]
    TextAligncenter,
    [Description("\uece1")]
    TextAlignleft,
    [Description("\uece2")]
    TextAlignright,
    [Description("\uece3")]
    TextAppend,
    [Description("\uece4")]
    TextBadgeCheckmark,
    [Description("\uece5")]
    TextBadgeMinus,
    [Description("\uece6")]
    TextBadgePlus,
    [Description("\uece7")]
    TextBadgeStar,
    [Description("\uece8")]
    TextBadgeXmark,
    [Description("\uece9")]
    Textbox,
    [Description("\uecea")]
    TextBubble,
    [Description("\ueceb")]
    TextBubbleFill,
    [Description("\uecec")]
    TextCursor,
    [Description("\ueced")]
    Textformat,
    [Description("\uecee")]
    Textformat123,
    [Description("\uecef")]
    TextformatAbc,
    [Description("\uecf0")]
    TextformatAbcDottedunderline,
    [Description("\uecf1")]
    TextformatAlt,
    [Description("\uecf2")]
    TextformatSize,
    [Description("\uecf3")]
    TextformatSubscript,
    [Description("\uecf4")]
    TextformatSuperscript,
    [Description("\uecf5")]
    TextInsert,
    [Description("\uecf6")]
    TextJustify,
    [Description("\uecf7")]
    TextJustifyleft,
    [Description("\uecf8")]
    TextJustifyright,
    [Description("\uecf9")]
    TextQuote,
    [Description("\uecfa")]
    Thermometer,
    [Description("\uecfb")]
    ThermometerSnowflake,
    [Description("\uecfc")]
    ThermometerSun,
    [Description("\uecfd")]
    Timelapse,
    [Description("\uecfe")]
    Timer,
    [Description("\uecff")]
    Tornado,
    [Description("\ued00")]
    Tortoise,
    [Description("\ued01")]
    TortoiseFill,
    [Description("\ued02")]
    TramFill,
    [Description("\ued03")]
    Trash,
    [Description("\ued04")]
    TrashCircle,
    [Description("\ued05")]
    TrashCircleFill,
    [Description("\ued06")]
    TrashFill,
    [Description("\ued07")]
    TrashSlash,
    [Description("\ued08")]
    TrashSlashFill,
    [Description("\ued09")]
    Tray,
    [Description("\ued0a")]
    Tray2,
    [Description("\ued0b")]
    Tray2Fill,
    [Description("\ued0c")]
    TrayArrowDown,
    [Description("\ued0d")]
    TrayArrowDownFill,
    [Description("\ued0e")]
    TrayArrowUp,
    [Description("\ued0f")]
    TrayArrowupFill,
    [Description("\ued10")]
    TrayFill,
    [Description("\ued11")]
    TrayFull,
    [Description("\ued12")]
    TrayFullFill,
    [Description("\ued13")]
    Triangle,
    [Description("\ued14")]
    TriangleFill,
    [Description("\ued15")]
    TriangleLefthalfFill,
    [Description("\ued16")]
    TriangleRighthalfFill,
    [Description("\ued17")]
    Tropicalstorm,
    [Description("\ued18")]
    Tuningfork,
    [Description("\ued19")]
    Tv,
    [Description("\ued1a")]
    TvCircle,
    [Description("\ued1b")]
    TvCircleFill,
    [Description("\ued1c")]
    TvFill,
    [Description("\ued1d")]
    TvMusicNote,
    [Description("\ued1e")]
    TvMusicNoteFill,
    [Description("\ued1f")]
    UiwindowSplit2x1,
    [Description("\ued20")]
    Umbrella,
    [Description("\ued21")]
    UmbrellaFill,
    [Description("\ued22")]
    Underline,
    [Description("\ued23")]
    View2d,
    [Description("\ued24")]
    View3d,
    [Description("\ued25")]
    Viewfinder,
    [Description("\ued26")]
    ViewfinderCircle,
    [Description("\ued27")]
    ViewfinderCircleFill,
    [Description("\ued28")]
    WandRays,
    [Description("\ued29")]
    WandRaysInverse,
    [Description("\ued2a")]
    WandStars,
    [Description("\ued2b")]
    WandStarsInverse,
    [Description("\ued2c")]
    Waveform,
    [Description("\ued2d")]
    WaveformCircle,
    [Description("\ued2e")]
    WaveformCircleFill,
    [Description("\ued2f")]
    WaveformPath,
    [Description("\ued30")]
    WaveformPathBadgeMinus,
    [Description("\ued31")]
    WaveformPathBadgePlus,
    [Description("\ued32")]
    WaveformPathEcg,
    [Description("\ued33")]
    Wifi,
    [Description("\ued34")]
    WifiExclamationmark,
    [Description("\ued35")]
    WifiSlash,
    [Description("\ued36")]
    Wind,
    [Description("\ued37")]
    WindSnow,
    [Description("\ued38")]
    Wrench,
    [Description("\ued39")]
    WrenchFill,
    [Description("\ued3a")]
    Xmark,
    [Description("\ued3b")]
    XmarkCircle,
    [Description("\ued3c")]
    XmarkCircleFill,
    [Description("\ued3d")]
    XmarkOctagon,
    [Description("\ued3e")]
    XmarkOctagonFill,
    [Description("\ued3f")]
    XmarkRectangle,
    [Description("\ued40")]
    XmarkRectangleFill,
    [Description("\ued41")]
    XmarkSeal,
    [Description("\ued42")]
    XmarkSealFill,
    [Description("\ued43")]
    XmarkShield,
    [Description("\ued44")]
    XmarkShieldFill,
    [Description("\ued45")]
    XmarkSquare,
    [Description("\ued46")]
    XmarkSquareFill,
    [Description("\ued47")]
    ZoomIn,
    [Description("\ued48")]
    ZoomOut,
    [Description("\ued49")]
    Zzz,
}
