using System.ComponentModel;

namespace MauiIcons.FontAwesome;
public enum FontAwesomeIcons
{
    [Description("\u0020")]
    Space,
    [Description("\u0021")]
    Exclamation,
    [Description("\u0023")]
    Hashtag,
    [Description("\u0024")]
    DollarSign,
    [Description("\u0025")]
    Percent,
    [Description("\u002a")]
    Asterisk,
    [Description("\u002b")]
    Plus,
    [Description("\u002d")]
    Hyphen,
    [Description("\u0030")]
    Zero,
    [Description("\u0031")]
    One,
    [Description("\u0032")]
    Two,
    [Description("\u0033")]
    Three,
    [Description("\u0034")]
    Four,
    [Description("\u0035")]
    Five,
    [Description("\u0036")]
    Six,
    [Description("\u0037")]
    Seven,
    [Description("\u0038")]
    Eight,
    [Description("\u0039")]
    Nine,
    [Description("\u003c")]
    LessThan,
    [Description("\u003d")]
    Equals,
    [Description("\u003e")]
    GreaterThan,
    [Description("\u003f")]
    Question,
    [Description("\u0040")]
    At,
    [Description("\u0041")]
    A,
    [Description("\u0042")]
    B,
    [Description("\u0043")]
    C,
    [Description("\u0044")]
    D,
    [Description("\u0045")]
    E,
    [Description("\u0046")]
    F,
    [Description("\u0047")]
    G,
    [Description("\u0048")]
    H,
    [Description("\u0049")]
    I,
    [Description("\u004a")]
    J,
    [Description("\u004b")]
    K,
    [Description("\u004c")]
    L,
    [Description("\u004d")]
    M,
    [Description("\u004e")]
    N,
    [Description("\u004f")]
    O,
    [Description("\u0050")]
    P,
    [Description("\u0051")]
    Q,
    [Description("\u0052")]
    R,
    [Description("\u0053")]
    S,
    [Description("\u0054")]
    T,
    [Description("\u0055")]
    U,
    [Description("\u0056")]
    V,
    [Description("\u0057")]
    W,
    [Description("\u0058")]
    X,
    [Description("\u0059")]
    Y,
    [Description("\u005a")]
    Z,
    [Description("\u0022")]
    ZeroWidthSpace,
    [Description("\ue185")]
    FolderClosed,
    [Description("\ue1fe")]
    Notdef,
    [Description("\u2665")]
    Heart,
    [Description("\u2b50")]
    Star,
    [Description("\uf007")]
    User,
    [Description("\uf017")]
    Clock,
    [Description("\uf022")]
    RectangleList,
    [Description("\uf024")]
    Flag,
    [Description("\uf02e")]
    Bookmark,
    [Description("\uf03e")]
    Image,
    [Description("\uf044")]
    PenToSquare,
    [Description("\uf057")]
    CircleXmark,
    [Description("\uf058")]
    CircleCheck,
    [Description("\uf059")]
    CircleQuestion,
    [Description("\uf06e")]
    Eye,
    [Description("\uf070")]
    EyeSlash,
    [Description("\uf073")]
    CalendarDays,
    [Description("\uf075")]
    Comment,
    [Description("\uf07b")]
    Folder,
    [Description("\uf07c")]
    FolderOpen,
    [Description("\uf080")]
    ChartBar,
    [Description("\uf086")]
    Comments,
    [Description("\uf089")]
    StarHalf,
    [Description("\uf094")]
    Lemon,
    [Description("\uf09d")]
    CreditCard,
    [Description("\uf0a0")]
    HardDrive,
    [Description("\uf0a4")]
    HandPointRight,
    [Description("\uf0a5")]
    HandPointLeft,
    [Description("\u261d")]
    HandPointUp,
    [Description("\uf0a7")]
    HandPointDown,
    [Description("\uf0c5")]
    Copy,
    [Description("\uf0c7")]
    FloppyDisk,
    [Description("\u25a0")]
    Square,
    [Description("\u2709")]
    Envelope,
    [Description("\uf0ea")]
    Paste,
    [Description("\uf0eb")]
    Lightbulb,
    [Description("\uf0a2")]
    Bell,
    [Description("\uf0f8")]
    Hospital,
    [Description("\uf0fe")]
    SquarePlus,
    [Description("\u25cf")]
    Circle,
    [Description("\uf118")]
    FaceSmile,
    [Description("\u2639")]
    FaceFrown,
    [Description("\uf11a")]
    FaceMeh,
    [Description("\u2328")]
    Keyboard,
    [Description("\uf133")]
    Calendar,
    [Description("\uf01d")]
    CirclePlay,
    [Description("\uf146")]
    SquareMinus,
    [Description("\u2611")]
    SquareCheck,
    [Description("\uf045")]
    ShareFromSquare,
    [Description("\uf14e")]
    Compass,
    [Description("\uf150")]
    SquareCaretDown,
    [Description("\uf151")]
    SquareCaretUp,
    [Description("\uf152")]
    SquareCaretRight,
    [Description("\uf016")]
    File,
    [Description("\uf0f6")]
    FileLines,
    [Description("\uf087")]
    ThumbsUp,
    [Description("\uf088")]
    ThumbsDown,
    [Description("\u2600")]
    Sun,
    [Description("\u23fe")]
    Moon,
    [Description("\uf191")]
    SquareCaretLeft,
    [Description("\uf192")]
    CircleDot,
    [Description("\uf0f7")]
    Building,
    [Description("\uf1c1")]
    FilePdf,
    [Description("\uf1c2")]
    FileWord,
    [Description("\uf1c3")]
    FileExcel,
    [Description("\uf1c4")]
    FilePowerpoint,
    [Description("\uf1c5")]
    FileImage,
    [Description("\uf1c6")]
    FileZipper,
    [Description("\uf1c7")]
    FileAudio,
    [Description("\uf1c8")]
    FileVideo,
    [Description("\uf1c9")]
    FileCode,
    [Description("\uf1cd")]
    LifeRing,
    [Description("\uf1d8")]
    PaperPlane,
    [Description("\u26bd")]
    Futbol,
    [Description("\uf1ea")]
    Newspaper,
    [Description("\uf1f6")]
    BellSlash,
    [Description("\u00a9")]
    Copyright,
    [Description("\uf20a")]
    ClosedCaptioning,
    [Description("\uf247")]
    ObjectGroup,
    [Description("\uf248")]
    ObjectUngroup,
    [Description("\uf249")]
    NoteSticky,
    [Description("\uf24d")]
    Clone,
    [Description("\uf252")]
    HourglassHalf,
    [Description("\u23f3")]
    Hourglass,
    [Description("\uf255")]
    HandBackFist,
    [Description("\u270b")]
    Hand,
    [Description("\uf257")]
    HandScissors,
    [Description("\uf258")]
    HandLizard,
    [Description("\uf259")]
    HandSpock,
    [Description("\uf25a")]
    HandPointer,
    [Description("\u270c")]
    HandPeace,
    [Description("\u00ae")]
    Registered,
    [Description("\uf271")]
    CalendarPlus,
    [Description("\uf272")]
    CalendarMinus,
    [Description("\uf273")]
    CalendarXmark,
    [Description("\uf274")]
    CalendarCheck,
    [Description("\uf278")]
    Map,
    [Description("\uf27a")]
    Message,
    [Description("\uf28b")]
    CirclePause,
    [Description("\uf28d")]
    CircleStop,
    [Description("\uf2b4")]
    FontAwesome,
    [Description("\uf2b5")]
    Handshake,
    [Description("\uf2b6")]
    EnvelopeOpen,
    [Description("\uf2b9")]
    AddressBook,
    [Description("\uf2bb")]
    AddressCard,
    [Description("\uf2bd")]
    CircleUser,
    [Description("\uf2c1")]
    IdBadge,
    [Description("\uf2c2")]
    IdCard,
    [Description("\uf2d0")]
    WindowMaximize,
    [Description("\uf2d1")]
    WindowMinimize,
    [Description("\uf2d2")]
    WindowRestore,
    [Description("\u2744")]
    Snowflake,
    [Description("\uf014")]
    TrashCan,
    [Description("\uf302")]
    Images,
    [Description("\uf328")]
    Clipboard,
    [Description("\uf01a")]
    CircleDown,
    [Description("\uf190")]
    CircleLeft,
    [Description("\uf18e")]
    CircleRight,
    [Description("\uf01b")]
    CircleUp,
    [Description("\uf3a5")]
    Gem,
    [Description("\uf3d1")]
    MoneyBill1,
    [Description("\uf2d4")]
    RectangleXmark,
    [Description("\u265d")]
    ChessBishop,
    [Description("\u265a")]
    ChessKing,
    [Description("\u265e")]
    ChessKnight,
    [Description("\u265f")]
    ChessPawn,
    [Description("\u265b")]
    ChessQueen,
    [Description("\u265c")]
    ChessRook,
    [Description("\u2b1b")]
    SquareFull,
    [Description("\uf27b")]
    CommentDots,
    [Description("\uf4da")]
    FaceSmileWink,
    [Description("\uf556")]
    FaceAngry,
    [Description("\uf567")]
    FaceDizzy,
    [Description("\uf579")]
    FaceFlushed,
    [Description("\uf57a")]
    FaceFrownOpen,
    [Description("\uf57f")]
    FaceGrimace,
    [Description("\uf580")]
    FaceGrin,
    [Description("\uf581")]
    FaceGrinWide,
    [Description("\uf582")]
    FaceGrinBeam,
    [Description("\uf583")]
    FaceGrinBeamSweat,
    [Description("\uf584")]
    FaceGrinHearts,
    [Description("\uf585")]
    FaceGrinSquint,
    [Description("\uf586")]
    FaceGrinSquintTears,
    [Description("\uf587")]
    FaceGrinStars,
    [Description("\uf588")]
    FaceGrinTears,
    [Description("\uf589")]
    FaceGrinTongue,
    [Description("\uf58a")]
    FaceGrinTongueSquint,
    [Description("\uf58b")]
    FaceGrinTongueWink,
    [Description("\uf58c")]
    FaceGrinWink,
    [Description("\uf596")]
    FaceKiss,
    [Description("\uf597")]
    FaceKissBeam,
    [Description("\uf598")]
    FaceKissWinkHeart,
    [Description("\uf599")]
    FaceLaugh,
    [Description("\uf59a")]
    FaceLaughBeam,
    [Description("\uf59b")]
    FaceLaughSquint,
    [Description("\uf59c")]
    FaceLaughWink,
    [Description("\uf5a4")]
    FaceMehBlank,
    [Description("\uf5a5")]
    FaceRollingEyes,
    [Description("\uf5b3")]
    FaceSadCry,
    [Description("\uf5b4")]
    FaceSadTear,
    [Description("\uf5b8")]
    FaceSmileBeam,
    [Description("\uf5c0")]
    StarHalfStroke,
    [Description("\uf5c2")]
    FaceSurprise,
    [Description("\uf5c8")]
    FaceTired,
}
