using System.ComponentModel;

namespace MauiIcons.FontAwesome.Brand;
public enum FontAwesomeBrandIcons
{
    [Description("\u0020")]
    Space,
    [Description("\u0021")]
    Exclamation,
    [Description("\u0023")]
    Hashtag,
    [Description("\u0024")]
    DollarSign,
    [Description("\u0025")]
    Percent,
    [Description("\u002a")]
    Asterisk,
    [Description("\u002b")]
    Plus,
    [Description("\u002d")]
    Hyphen,
    [Description("\u0030")]
    Zero,
    [Description("\u0031")]
    One,
    [Description("\u0032")]
    Two,
    [Description("\u0033")]
    Three,
    [Description("\u0034")]
    Four,
    [Description("\u0035")]
    Five,
    [Description("\u0036")]
    Six,
    [Description("\u0037")]
    Seven,
    [Description("\u0038")]
    Eight,
    [Description("\u0039")]
    Nine,
    [Description("\u003c")]
    LessThan,
    [Description("\u003d")]
    Equals,
    [Description("\u003e")]
    GreaterThan,
    [Description("\u003f")]
    Question,
    [Description("\u0040")]
    At,
    [Description("\u0041")]
    A,
    [Description("\u0042")]
    B,
    [Description("\u0043")]
    C,
    [Description("\u0044")]
    D,
    [Description("\u0045")]
    E,
    [Description("\u0046")]
    F,
    [Description("\u0047")]
    G,
    [Description("\u0048")]
    H,
    [Description("\u0049")]
    I,
    [Description("\u004a")]
    J,
    [Description("\u004b")]
    K,
    [Description("\u004c")]
    L,
    [Description("\u004d")]
    M,
    [Description("\u004e")]
    N,
    [Description("\u004f")]
    O,
    [Description("\u0050")]
    P,
    [Description("\u0051")]
    Q,
    [Description("\u0052")]
    R,
    [Description("\u0053")]
    S,
    [Description("\u0054")]
    T,
    [Description("\u0055")]
    U,
    [Description("\u0056")]
    V,
    [Description("\u0057")]
    W,
    [Description("\u0058")]
    X,
    [Description("\u0059")]
    Y,
    [Description("\u005a")]
    Z,
    [Description("\u0022")]
    ZeroWidthSpace,
    [Description("\ue007")]
    FirefoxBrowser,
    [Description("\ue013")]
    Ideal,
    [Description("\ue01a")]
    Microblog,
    [Description("\ue01e")]
    SquarePiedPiper,
    [Description("\ue049")]
    Unity,
    [Description("\ue052")]
    Dailymotion,
    [Description("\ue055")]
    SquareInstagram,
    [Description("\ue056")]
    Mixer,
    [Description("\ue057")]
    Shopify,
    [Description("\ue077")]
    Deezer,
    [Description("\ue078")]
    EdgeLegacy,
    [Description("\ue079")]
    GooglePay,
    [Description("\ue07a")]
    Rust,
    [Description("\ue07b")]
    Tiktok,
    [Description("\ue07c")]
    Unsplash,
    [Description("\ue07d")]
    Cloudflare,
    [Description("\ue07e")]
    Guilded,
    [Description("\ue07f")]
    Hive,
    [Description("\ue080")]
    _42Group,
    [Description("\ue081")]
    Instalod,
    [Description("\ue082")]
    OctopusDeploy,
    [Description("\ue083")]
    Perbyte,
    [Description("\ue084")]
    Uncharted,
    [Description("\ue087")]
    WatchmanMonitoring,
    [Description("\ue088")]
    Wodu,
    [Description("\ue1fe")]
    Notdef,
    [Description("\ue2d0")]
    Wirsindhandwerk,
    [Description("\ue340")]
    Bots,
    [Description("\ue360")]
    Cmplid,
    [Description("\ue3d9")]
    Bilibili,
    [Description("\ue40f")]
    Golang,
    [Description("\ue43a")]
    Pix,
    [Description("\ue44a")]
    Sitrox,
    [Description("\ue499")]
    Hashnode,
    [Description("\ue49b")]
    Meta,
    [Description("\ue4a0")]
    Padlet,
    [Description("\ue530")]
    NfcDirectional,
    [Description("\ue531")]
    NfcSymbol,
    [Description("\ue570")]
    Screenpal,
    [Description("\ue5ac")]
    SpaceAwesome,
    [Description("\ue5ad")]
    SquareFontAwesome,
    [Description("\ue5ae")]
    SquareGitlab,
    [Description("\ue5c6")]
    Odysee,
    [Description("\ue5c7")]
    Stubber,
    [Description("\ue60b")]
    Debian,
    [Description("\ue60c")]
    Shoelace,
    [Description("\ue618")]
    Threads,
    [Description("\ue619")]
    SquareThreads,
    [Description("\ue61a")]
    SquareXTwitter,
    [Description("\ue61b")]
    XTwitter,
    [Description("\ue62b")]
    Opensuse,
    [Description("\ue62d")]
    Letterboxd,
    [Description("\ue62e")]
    SquareLetterboxd,
    [Description("\ue62f")]
    Mintbit,
    [Description("\ue63b")]
    GoogleScholar,
    [Description("\ue63c")]
    Brave,
    [Description("\ue63d")]
    BraveReverse,
    [Description("\ue640")]
    Pixiv,
    [Description("\ue641")]
    Upwork,
    [Description("\ue65c")]
    Webflow,
    [Description("\ue663")]
    SignalMessenger,
    [Description("\uf081")]
    SquareTwitter,
    [Description("\uf082")]
    SquareFacebook,
    [Description("\uf08c")]
    Linkedin,
    [Description("\uf092")]
    SquareGithub,
    [Description("\uf099")]
    Twitter,
    [Description("\uf09a")]
    Facebook,
    [Description("\uf09b")]
    Github,
    [Description("\uf0d2")]
    Pinterest,
    [Description("\uf0d3")]
    SquarePinterest,
    [Description("\uf0d4")]
    SquareGooglePlus,
    [Description("\uf0d5")]
    GooglePlusG,
    [Description("\uf0e1")]
    LinkedinIn,
    [Description("\uf113")]
    GithubAlt,
    [Description("\uf136")]
    Maxcdn,
    [Description("\uf13b")]
    Html5,
    [Description("\uf13c")]
    Css3,
    [Description("\uf15a")]
    Btc,
    [Description("\uf167")]
    Youtube,
    [Description("\uf168")]
    Xing,
    [Description("\uf169")]
    SquareXing,
    [Description("\uf16b")]
    Dropbox,
    [Description("\uf16c")]
    StackOverflow,
    [Description("\uf16d")]
    Instagram,
    [Description("\uf16e")]
    Flickr,
    [Description("\uf170")]
    Adn,
    [Description("\uf171")]
    Bitbucket,
    [Description("\uf173")]
    Tumblr,
    [Description("\uf174")]
    SquareTumblr,
    [Description("\uf179")]
    Apple,
    [Description("\uf17a")]
    Windows,
    [Description("\uf17b")]
    Android,
    [Description("\uf17c")]
    Linux,
    [Description("\uf17d")]
    Dribbble,
    [Description("\uf17e")]
    Skype,
    [Description("\uf180")]
    Foursquare,
    [Description("\uf181")]
    Trello,
    [Description("\uf184")]
    Gratipay,
    [Description("\uf189")]
    Vk,
    [Description("\uf18a")]
    Weibo,
    [Description("\uf18b")]
    Renren,
    [Description("\uf18c")]
    Pagelines,
    [Description("\uf18d")]
    StackExchange,
    [Description("\uf194")]
    SquareVimeo,
    [Description("\uf198")]
    Slack,
    [Description("\uf19a")]
    Wordpress,
    [Description("\uf19b")]
    Openid,
    [Description("\uf19e")]
    Yahoo,
    [Description("\uf1a0")]
    Google,
    [Description("\uf1a1")]
    Reddit,
    [Description("\uf1a2")]
    SquareReddit,
    [Description("\uf1a3")]
    StumbleuponCircle,
    [Description("\uf1a4")]
    Stumbleupon,
    [Description("\uf1a5")]
    Delicious,
    [Description("\uf1a6")]
    Digg,
    [Description("\uf1a7")]
    PiedPiperPp,
    [Description("\uf1a8")]
    PiedPiperAlt,
    [Description("\uf1a9")]
    Drupal,
    [Description("\uf1aa")]
    Joomla,
    [Description("\uf1b4")]
    Behance,
    [Description("\uf1b5")]
    SquareBehance,
    [Description("\uf1b6")]
    Steam,
    [Description("\uf1b7")]
    SquareSteam,
    [Description("\uf1bc")]
    Spotify,
    [Description("\uf1bd")]
    Deviantart,
    [Description("\uf1be")]
    Soundcloud,
    [Description("\uf1ca")]
    Vine,
    [Description("\uf1cb")]
    Codepen,
    [Description("\uf1cc")]
    Jsfiddle,
    [Description("\uf1d0")]
    Rebel,
    [Description("\uf1d1")]
    Empire,
    [Description("\uf1d2")]
    SquareGit,
    [Description("\uf1d3")]
    Git,
    [Description("\uf1d4")]
    HackerNews,
    [Description("\uf1d5")]
    TencentWeibo,
    [Description("\uf1d6")]
    Qq,
    [Description("\uf1d7")]
    Weixin,
    [Description("\uf1e7")]
    Slideshare,
    [Description("\uf1e8")]
    Twitch,
    [Description("\uf1e9")]
    Yelp,
    [Description("\uf1ed")]
    Paypal,
    [Description("\uf1ee")]
    GoogleWallet,
    [Description("\uf1f0")]
    CcVisa,
    [Description("\uf1f1")]
    CcMastercard,
    [Description("\uf1f2")]
    CcDiscover,
    [Description("\uf1f3")]
    CcAmex,
    [Description("\uf1f4")]
    CcPaypal,
    [Description("\uf1f5")]
    CcStripe,
    [Description("\uf202")]
    Lastfm,
    [Description("\uf203")]
    SquareLastfm,
    [Description("\uf208")]
    Ioxhost,
    [Description("\uf209")]
    Angellist,
    [Description("\uf20d")]
    Buysellads,
    [Description("\uf20e")]
    Connectdevelop,
    [Description("\uf210")]
    Dashcube,
    [Description("\uf211")]
    Forumbee,
    [Description("\uf212")]
    Leanpub,
    [Description("\uf213")]
    Sellsy,
    [Description("\uf214")]
    Shirtsinbulk,
    [Description("\uf215")]
    Simplybuilt,
    [Description("\uf216")]
    Skyatlas,
    [Description("\uf231")]
    PinterestP,
    [Description("\uf232")]
    Whatsapp,
    [Description("\uf237")]
    Viacoin,
    [Description("\uf23a")]
    Medium,
    [Description("\uf23b")]
    YCombinator,
    [Description("\uf23c")]
    OptinMonster,
    [Description("\uf23d")]
    Opencart,
    [Description("\uf23e")]
    Expeditedssl,
    [Description("\uf24b")]
    CcJcb,
    [Description("\uf24c")]
    CcDinersClub,
    [Description("\uf25e")]
    CreativeCommons,
    [Description("\uf260")]
    Gg,
    [Description("\uf261")]
    GgCircle,
    [Description("\uf263")]
    Odnoklassniki,
    [Description("\uf264")]
    SquareOdnoklassniki,
    [Description("\uf265")]
    GetPocket,
    [Description("\uf266")]
    WikipediaW,
    [Description("\uf267")]
    Safari,
    [Description("\uf268")]
    Chrome,
    [Description("\uf269")]
    Firefox,
    [Description("\uf26a")]
    Opera,
    [Description("\uf26b")]
    InternetExplorer,
    [Description("\uf26d")]
    Contao,
    [Description("\uf26e")]
    _500px,
    [Description("\uf270")]
    Amazon,
    [Description("\uf27c")]
    Houzz,
    [Description("\uf27d")]
    VimeoV,
    [Description("\uf27e")]
    BlackTie,
    [Description("\uf280")]
    Fonticons,
    [Description("\uf281")]
    RedditAlien,
    [Description("\uf282")]
    Edge,
    [Description("\uf284")]
    Codiepie,
    [Description("\uf285")]
    Modx,
    [Description("\uf286")]
    FortAwesome,
    [Description("\uf287")]
    Usb,
    [Description("\uf288")]
    ProductHunt,
    [Description("\uf289")]
    Mixcloud,
    [Description("\uf28a")]
    Scribd,
    [Description("\uf293")]
    Bluetooth,
    [Description("\uf294")]
    BluetoothB,
    [Description("\uf296")]
    Gitlab,
    [Description("\uf297")]
    Wpbeginner,
    [Description("\uf298")]
    Wpforms,
    [Description("\uf299")]
    Envira,
    [Description("\uf2a5")]
    Glide,
    [Description("\uf2a6")]
    GlideG,
    [Description("\uf2a9")]
    Viadeo,
    [Description("\uf2aa")]
    SquareViadeo,
    [Description("\uf2ab")]
    Snapchat,
    [Description("\uf2ad")]
    SquareSnapchat,
    [Description("\uf2ae")]
    PiedPiper,
    [Description("\uf2b0")]
    FirstOrder,
    [Description("\uf2b1")]
    Yoast,
    [Description("\uf2b2")]
    Themeisle,
    [Description("\uf2b3")]
    GooglePlus,
    [Description("\uf2b4")]
    FontAwesome,
    [Description("\uf2b8")]
    Linode,
    [Description("\uf2c4")]
    Quora,
    [Description("\uf2c5")]
    FreeCodeCamp,
    [Description("\uf2c6")]
    Telegram,
    [Description("\uf2d5")]
    Bandcamp,
    [Description("\uf2d6")]
    Grav,
    [Description("\uf2d7")]
    Etsy,
    [Description("\uf2d8")]
    Imdb,
    [Description("\uf2d9")]
    Ravelry,
    [Description("\uf2da")]
    Sellcast,
    [Description("\uf2dd")]
    Superpowers,
    [Description("\uf2de")]
    Wpexplorer,
    [Description("\uf2e0")]
    Meetup,
    [Description("\uf35c")]
    SquareFontAwesomeStroke,
    [Description("\uf29b")]
    AccessibleIcon,
    [Description("\uf369")]
    Accusoft,
    [Description("\uf36a")]
    Adversal,
    [Description("\uf36b")]
    Affiliatetheme,
    [Description("\uf36c")]
    Algolia,
    [Description("\uf36d")]
    Amilia,
    [Description("\uf36e")]
    Angrycreative,
    [Description("\uf36f")]
    AppStore,
    [Description("\uf370")]
    AppStoreIos,
    [Description("\uf371")]
    Apper,
    [Description("\uf372")]
    Asymmetrik,
    [Description("\uf373")]
    Audible,
    [Description("\uf374")]
    Avianex,
    [Description("\uf375")]
    Aws,
    [Description("\uf378")]
    Bimobject,
    [Description("\uf379")]
    Bitcoin,
    [Description("\uf37a")]
    Bity,
    [Description("\uf37b")]
    Blackberry,
    [Description("\uf37c")]
    Blogger,
    [Description("\uf37d")]
    BloggerB,
    [Description("\uf37f")]
    Buromobelexperte,
    [Description("\uf380")]
    Centercode,
    [Description("\uf383")]
    Cloudscale,
    [Description("\uf384")]
    Cloudsmith,
    [Description("\uf385")]
    Cloudversify,
    [Description("\uf388")]
    Cpanel,
    [Description("\uf38b")]
    Css3Alt,
    [Description("\uf38c")]
    Cuttlefish,
    [Description("\uf38d")]
    DAndD,
    [Description("\uf38e")]
    Deploydog,
    [Description("\uf38f")]
    Deskpro,
    [Description("\uf391")]
    DigitalOcean,
    [Description("\uf392")]
    Discord,
    [Description("\uf393")]
    Discourse,
    [Description("\uf394")]
    Dochub,
    [Description("\uf395")]
    Docker,
    [Description("\uf396")]
    Draft2digital,
    [Description("\uf397")]
    SquareDribbble,
    [Description("\uf399")]
    Dyalog,
    [Description("\uf39a")]
    Earlybirds,
    [Description("\uf39d")]
    Erlang,
    [Description("\uf39e")]
    FacebookF,
    [Description("\uf39f")]
    FacebookMessenger,
    [Description("\uf3a1")]
    Firstdraft,
    [Description("\uf3a2")]
    FonticonsFi,
    [Description("\uf3a3")]
    FortAwesomeAlt,
    [Description("\uf3a4")]
    Freebsd,
    [Description("\uf3a6")]
    Gitkraken,
    [Description("\uf3a7")]
    Gofore,
    [Description("\uf3a8")]
    Goodreads,
    [Description("\uf3a9")]
    GoodreadsG,
    [Description("\uf3aa")]
    GoogleDrive,
    [Description("\uf3ab")]
    GooglePlay,
    [Description("\uf3ac")]
    Gripfire,
    [Description("\uf3ad")]
    Grunt,
    [Description("\uf3ae")]
    Gulp,
    [Description("\uf3af")]
    SquareHackerNews,
    [Description("\uf3b0")]
    HireAHelper,
    [Description("\uf3b1")]
    Hotjar,
    [Description("\uf3b2")]
    Hubspot,
    [Description("\uf3b4")]
    Itunes,
    [Description("\uf3b5")]
    ItunesNote,
    [Description("\uf3b6")]
    Jenkins,
    [Description("\uf3b7")]
    Joget,
    [Description("\uf3b8")]
    Js,
    [Description("\uf3b9")]
    SquareJs,
    [Description("\uf3ba")]
    Keycdn,
    [Description("\uf3bb")]
    Kickstarter,
    [Description("\uf3bc")]
    KickstarterK,
    [Description("\uf3bd")]
    Laravel,
    [Description("\uf3c0")]
    Line,
    [Description("\uf3c3")]
    Lyft,
    [Description("\uf3c4")]
    Magento,
    [Description("\uf3c6")]
    Medapps,
    [Description("\uf3c8")]
    Medrt,
    [Description("\uf3ca")]
    Microsoft,
    [Description("\uf3cb")]
    Mix,
    [Description("\uf3cc")]
    Mizuni,
    [Description("\uf3d0")]
    Monero,
    [Description("\uf3d2")]
    Napster,
    [Description("\uf3d3")]
    NodeJs,
    [Description("\uf3d4")]
    Npm,
    [Description("\uf3d5")]
    Ns8,
    [Description("\uf3d6")]
    Nutritionix,
    [Description("\uf3d7")]
    Page4,
    [Description("\uf3d8")]
    Palfed,
    [Description("\uf3d9")]
    Patreon,
    [Description("\uf3da")]
    Periscope,
    [Description("\uf3db")]
    Phabricator,
    [Description("\uf3dc")]
    PhoenixFramework,
    [Description("\uf3df")]
    Playstation,
    [Description("\uf3e1")]
    Pushed,
    [Description("\uf3e2")]
    Python,
    [Description("\uf3e3")]
    RedRiver,
    [Description("\uf3e4")]
    Wpressr,
    [Description("\uf3e6")]
    Replyd,
    [Description("\uf3e7")]
    Resolving,
    [Description("\uf3e8")]
    Rocketchat,
    [Description("\uf3e9")]
    Rockrms,
    [Description("\uf3ea")]
    Schlix,
    [Description("\uf3eb")]
    Searchengin,
    [Description("\uf3ec")]
    Servicestack,
    [Description("\uf3ee")]
    Sistrix,
    [Description("\uf3f3")]
    Speakap,
    [Description("\uf3f5")]
    Staylinked,
    [Description("\uf3f6")]
    SteamSymbol,
    [Description("\uf3f7")]
    StickerMule,
    [Description("\uf3f8")]
    Studiovinari,
    [Description("\uf3f9")]
    Supple,
    [Description("\uf402")]
    Uber,
    [Description("\uf403")]
    Uikit,
    [Description("\uf404")]
    Uniregistry,
    [Description("\uf405")]
    Untappd,
    [Description("\uf407")]
    Ussunnah,
    [Description("\uf408")]
    Vaadin,
    [Description("\uf409")]
    Viber,
    [Description("\uf40a")]
    Vimeo,
    [Description("\uf40b")]
    Vnv,
    [Description("\uf40c")]
    SquareWhatsapp,
    [Description("\uf40d")]
    Whmcs,
    [Description("\uf411")]
    WordpressSimple,
    [Description("\uf412")]
    Xbox,
    [Description("\uf413")]
    Yandex,
    [Description("\uf414")]
    YandexInternational,
    [Description("\uf415")]
    ApplePay,
    [Description("\uf416")]
    CcApplePay,
    [Description("\uf417")]
    Fly,
    [Description("\uf419")]
    Node,
    [Description("\uf41a")]
    Osi,
    [Description("\uf41b")]
    React,
    [Description("\uf41c")]
    Autoprefixer,
    [Description("\uf41d")]
    Less,
    [Description("\uf41e")]
    Sass,
    [Description("\uf41f")]
    Vuejs,
    [Description("\uf420")]
    Angular,
    [Description("\uf421")]
    Aviato,
    [Description("\uf423")]
    Ember,
    [Description("\uf426")]
    Gitter,
    [Description("\uf427")]
    Hooli,
    [Description("\uf428")]
    Strava,
    [Description("\uf429")]
    Stripe,
    [Description("\uf42a")]
    StripeS,
    [Description("\uf42b")]
    Typo3,
    [Description("\uf42c")]
    AmazonPay,
    [Description("\uf42d")]
    CcAmazonPay,
    [Description("\uf42e")]
    Ethereum,
    [Description("\uf42f")]
    Korvue,
    [Description("\uf430")]
    Elementor,
    [Description("\uf166")]
    SquareYoutube,
    [Description("\uf44d")]
    Flipboard,
    [Description("\uf452")]
    Hips,
    [Description("\uf457")]
    Php,
    [Description("\uf459")]
    Quinscape,
    [Description("\uf4d5")]
    Readme,
    [Description("\uf4e4")]
    Java,
    [Description("\uf4e5")]
    PiedPiperHat,
    [Description("\uf4e7")]
    CreativeCommonsBy,
    [Description("\uf4e8")]
    CreativeCommonsNc,
    [Description("\uf4e9")]
    CreativeCommonsNcEu,
    [Description("\uf4ea")]
    CreativeCommonsNcJp,
    [Description("\uf4eb")]
    CreativeCommonsNd,
    [Description("\uf4ec")]
    CreativeCommonsPd,
    [Description("\uf4ed")]
    CreativeCommonsPdAlt,
    [Description("\uf4ee")]
    CreativeCommonsRemix,
    [Description("\uf4ef")]
    CreativeCommonsSa,
    [Description("\uf4f0")]
    CreativeCommonsSampling,
    [Description("\uf4f1")]
    CreativeCommonsSamplingPlus,
    [Description("\uf4f2")]
    CreativeCommonsShare,
    [Description("\uf4f3")]
    CreativeCommonsZero,
    [Description("\uf4f4")]
    Ebay,
    [Description("\uf4f5")]
    Keybase,
    [Description("\uf4f6")]
    Mastodon,
    [Description("\uf4f7")]
    RProject,
    [Description("\uf4f8")]
    Researchgate,
    [Description("\uf4f9")]
    Teamspeak,
    [Description("\uf50a")]
    FirstOrderAlt,
    [Description("\uf50b")]
    Fulcrum,
    [Description("\uf50c")]
    GalacticRepublic,
    [Description("\uf50d")]
    GalacticSenate,
    [Description("\uf50e")]
    JediOrder,
    [Description("\uf50f")]
    Mandalorian,
    [Description("\uf510")]
    OldRepublic,
    [Description("\uf511")]
    PhoenixSquadron,
    [Description("\uf512")]
    Sith,
    [Description("\uf513")]
    TradeFederation,
    [Description("\uf514")]
    WolfPackBattalion,
    [Description("\uf592")]
    Hornbill,
    [Description("\uf59e")]
    Mailchimp,
    [Description("\uf5a3")]
    Megaport,
    [Description("\uf5a8")]
    Nimblr,
    [Description("\uf5b2")]
    Rev,
    [Description("\uf5b5")]
    Shopware,
    [Description("\uf5be")]
    Squarespace,
    [Description("\uf5c6")]
    Themeco,
    [Description("\uf5cc")]
    Weebly,
    [Description("\uf5cf")]
    Wix,
    [Description("\uf5f1")]
    Ello,
    [Description("\uf5f7")]
    Hackerrank,
    [Description("\uf5fa")]
    Kaggle,
    [Description("\uf60f")]
    Markdown,
    [Description("\uf612")]
    Neos,
    [Description("\uf63f")]
    Zhihu,
    [Description("\uf642")]
    Alipay,
    [Description("\uf69d")]
    TheRedYeti,
    [Description("\uf6c9")]
    CriticalRole,
    [Description("\uf6ca")]
    DAndDBeyond,
    [Description("\uf6cc")]
    Dev,
    [Description("\uf6dc")]
    FantasyFlightGames,
    [Description("\uf730")]
    WizardsOfTheCoast,
    [Description("\uf731")]
    ThinkPeaks,
    [Description("\uf75d")]
    Reacteurope,
    [Description("\uf77a")]
    Artstation,
    [Description("\uf77b")]
    Atlassian,
    [Description("\uf785")]
    CanadianMapleLeaf,
    [Description("\uf789")]
    Centos,
    [Description("\uf78d")]
    Confluence,
    [Description("\uf790")]
    Dhl,
    [Description("\uf791")]
    Diaspora,
    [Description("\uf797")]
    Fedex,
    [Description("\uf798")]
    Fedora,
    [Description("\uf799")]
    Figma,
    [Description("\uf7af")]
    Intercom,
    [Description("\uf7b0")]
    Invision,
    [Description("\uf7b1")]
    Jira,
    [Description("\uf7b3")]
    Mendeley,
    [Description("\uf7bb")]
    RaspberryPi,
    [Description("\uf7bc")]
    Redhat,
    [Description("\uf7c6")]
    Sketch,
    [Description("\uf7d3")]
    Sourcetree,
    [Description("\uf7d6")]
    Suse,
    [Description("\uf7df")]
    Ubuntu,
    [Description("\uf7e0")]
    Ups,
    [Description("\uf7e1")]
    Usps,
    [Description("\uf7e3")]
    Yarn,
    [Description("\uf834")]
    Airbnb,
    [Description("\uf835")]
    BattleNet,
    [Description("\uf836")]
    Bootstrap,
    [Description("\uf837")]
    Buffer,
    [Description("\uf838")]
    Chromecast,
    [Description("\uf839")]
    Evernote,
    [Description("\uf83a")]
    ItchIo,
    [Description("\uf83b")]
    Salesforce,
    [Description("\uf83c")]
    SpeakerDeck,
    [Description("\uf83d")]
    Symfony,
    [Description("\uf83f")]
    Waze,
    [Description("\uf840")]
    Yammer,
    [Description("\uf841")]
    GitAlt,
    [Description("\uf842")]
    Stackpath,
    [Description("\uf89e")]
    CottonBureau,
    [Description("\uf8a6")]
    BuyNLarge,
    [Description("\uf8ca")]
    Mdb,
    [Description("\uf8d2")]
    Orcid,
    [Description("\uf8e1")]
    Swift,
    [Description("\uf8e8")]
    Umbraco,
}
